version: "3"
services:
  pytorch-docker-compose:
      container_name: pytorch-docker-compose
      build: .
      volumes:
        - .:/home/jovyan/work
      ports:
        - "8888:8888"
        - "6006:6006"
      environment:
        - JUPYTER_ENABLE_LAB=yes
      deploy:
        resources:
          reservations:
            devices:
            -  driver: nvidia
               count: all
               capabilities: [gpu]
